Sprint 2
PLA25/User-Manual pull request #2
Opened 2018-04-20 07:12 UTC by ThomAat2

2018-04-22 07:43 UTC, mvegter requested changes
Kijk nogmaals in bijlage B van de studiehandleiding, met name naar Instructions.

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
> +\date{January 5th, 2018}
Date wordt door LaTeX geregeld, dus niet handmatig toevoegen!

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
>  \subsection{Our product}
Geen leestekens in kopjes, let ook op de hoofdletters

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
> +On the top of this website there is a navigation bar, which is used to visit the several available pages. These pages include: the home page the map page and (if you are an admin) the admin page.
Geen haakjes gebruiken dit leest niet prettig.

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
> +\\
Hoe kom ik op de map-page?

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
> +\subsubsection{Nog meer kaarten}
Geen Nederlands!

2018-04-22 07:43 UTC, mvegter commented on latex/main.tex
> +This page is used to make changes to the system, e.g. user management. Just like the name says, this page is only available for admins.
Hoe kom ik op de admin-page?

2018-04-22 14:10 UTC, ThomAat2 commented on latex/main.tex
> +\subsubsection{Nog meer kaarten}
Dat is tijdelijk

2018-04-23 15:02 UTC, mvegter commented on latex/main.tex
> +% Er moet nog een afsluiter komen volgens de studiehandleiding.
Dus ...

2018-04-23 15:03 UTC, mvegter commented on latex/main.tex
>  \section{The website and how it works}
In dit hoofdstuk ga je al uitleggen hoe het werk, dat is ook het doel van de handleiding, dus dat voelt erg dubbel.

2018-04-23 15:04 UTC, mvegter commented on latex/main.tex
> +This will redirect you to the home page.
Dit is ook een stap in je lijst, namelijk de laatste.

2018-04-23 15:06 UTC, mvegter commented on latex/main.tex
> +The heatmap shows a representation of the temperature, using colors scaling from bright pink (cold) to red (warm). The colours are displayed on the map as a layer over the standard map.
Maak een gebruik van een afbeelding om je punt te verduidelijken.

2018-04-23 15:07 UTC, mvegter commented on latex/main.tex
> +% \section{Afsluiter}
Ondanks dat het comment is, alsnog in het Engels

2018-04-24 08:33 UTC, mvegter requested changes

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
>  \setcounter{page}{0}
Voorblad is een pagina, dus niet opnieuw beginnen met tellen.

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
> +\begin{tabbing}
Inspringing?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
>  \clearpage
Wat moet je 'clear'-en?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
> +~\\\\
Waarom zoveel ruimte tussen het kopje en de bijbehorende tekst?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
Gebruik de lipsum-package, zie [LaTeX: Generate dummy text](http://blog.chapagain.com.np/latex-generate-dummy-text-lorem-ipsum-in-your-document/).

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
> +\item Use the upper input field for your username.
Inspringing?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
>  \subsection{Login and the home page}
Zijn dit niet twee losse kopjes?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
> +\\
Gebruik `\newline` i.p.v. `\\`, dat leest makkelijker.

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
>  \subsection{The map page}
Misschien op een nieuwe pagina zetten?

2018-04-24 08:33 UTC, mvegter commented on latex/main.tex
>  ~\\
De handleiding is er om de gebruiker uit te leggen hoe alles werkt, om dan nog in de titel van een hoofdstuk te zeggen "and how it works" is erg dubbel.

2018-04-24 12:33 UTC, mvegter approved these changes

2018-04-24 12:33 UTC, merged